FROM mcr.microsoft.com/playwright:v1.56.1-noble

WORKDIR /app

COPY package*.json /app/

RUN npm config set registry https://registry.npmmirror.com/
RUN npm install

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
