// This file is auto-generated by @hey-api/openapi-ts

export type ApiCreate = {
    group?: string;
    name: string;
    path: string;
    method: string;
};

export type ApiPublic = {
    id: string;
    group: string;
    name: string;
    path: string;
    method: string;
    owner?: (UserPublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ApiTreeNode = {
    key: string;
    data: {
        [key: string]: unknown;
    };
    children?: Array<ApiTreeNode>;
};

export type ApiTreePublic = {
    data: Array<ApiTreeNode>;
    total: number;
};

export type ApiUpdate = {
    group?: (string | null);
    name?: (string | null);
    path?: (string | null);
    method?: (string | null);
};

export type ApplicationCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

export type ApplicationPrivate = {
    id: string;
    name: string;
    description?: (string | null);
    is_active: boolean;
    app_id: string;
    owner?: (UserPublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    app_key: string;
};

export type ApplicationPublic = {
    id: string;
    name: string;
    description?: (string | null);
    is_active: boolean;
    app_id: string;
    owner?: (UserPublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ApplicationsPublic = {
    applications: Array<ApplicationPublic>;
    total: number;
};

export type ApplicationUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type Body_Login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_User_upload_avatar = {
    file: (Blob | File);
};

export type GroupCreate = {
    name: string;
    description?: (string | null);
    member_ids?: (Array<(string)> | null);
};

export type GroupPublic = {
    id: string;
    name: string;
    description?: (string | null);
    owner?: (UserPublic | null);
    members?: (Array<UserPublic> | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type GroupsPublic = {
    groups: Array<GroupPublic>;
    total: number;
};

export type GroupUpdate = {
    name?: (string | null);
    description?: (string | null);
    owner_id?: (string | null);
    member_ids?: (Array<(string)> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    name: string;
    description?: (string | null);
};

export type ItemPublic = {
    id: string;
    name: string;
    description?: (string | null);
    owner?: (UserPublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ItemsPublic = {
    items: Array<ItemPublic>;
    total: number;
};

export type ItemUpdate = {
    name?: (string | null);
    description?: (string | null);
    owner_id?: (string | null);
};

export type MenuCreate = {
    label: string;
    icon?: (string | null);
    to?: (string | null);
    url?: (string | null);
    target?: (string | null);
    component?: (string | null);
    clazz?: (string | null);
    is_hidden?: boolean;
    parent_id?: (string | null);
};

export type MenuTreeNode = {
    id: string;
    label: string;
    icon?: (string | null);
    to?: (string | null);
    url?: (string | null);
    target?: (string | null);
    component?: (string | null);
    clazz?: (string | null);
    is_hidden: boolean;
    parent_id?: (string | null);
    items?: (Array<MenuTreeNode> | null);
};

export type MenuUpdate = {
    label?: (string | null);
    icon?: (string | null);
    to?: (string | null);
    url?: (string | null);
    target?: (string | null);
    component?: (string | null);
    clazz?: (string | null);
    is_hidden?: (boolean | null);
    parent_id?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * 周期任务调度类型
 */
export type PeriodicScheduleType = 'crontab' | 'interval';

export type Policy = {
    sub: string;
    obj: string;
    act: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
};

export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type RolesPublic = {
    roles: Array<RolePublic>;
    total: number;
};

export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type SettingsUpdate = {
    PROJECT_NAME?: (string | null);
    SENTRY_DSN?: (string | null);
    SMTP_HOST?: (string | null);
    SMTP_PORT?: (number | null);
    SMTP_USER?: (string | null);
    SMTP_PASSWORD?: (string | null);
    SMTP_TLS?: (boolean | null);
    SMTP_SSL?: (boolean | null);
    EMAILS_FROM_EMAIL?: (string | null);
    EMAILS_FROM_NAME?: (string | null);
    OIDC_ENABLED?: (boolean | null);
    OIDC_NAME?: (string | null);
    OIDC_AUTH_URL?: (string | null);
    OIDC_TOKEN_URL?: (string | null);
    OIDC_USERINFO_URL?: (string | null);
    OIDC_CLIENT_ID?: (string | null);
    OIDC_CLIENT_SECRET?: (string | null);
    OIDC_SCOPES?: (string | null);
    SIGNOUT_REDIRECT_URL?: (string | null);
    AUTO_LOGIN?: (boolean | null);
    LDAP_ENABLED?: (boolean | null);
    LDAP_HOST?: (string | null);
    LDAP_PORT?: (number | null);
    LDAP_BIND_DN?: (string | null);
    LDAP_BIND_PASSWORD?: (string | null);
    LDAP_BASE_DN?: (string | null);
    LDAP_USER_FILTER?: (string | null);
    LDAP_EMAIL_ATTRIBUTE?: (string | null);
    LDAP_USERNAME_ATTRIBUTE?: (string | null);
    LDAP_FULLNAME_ATTRIBUTE?: (string | null);
};

export type TaskCreate = {
    name: string;
    description?: (string | null);
    task_type?: TaskType;
    celery_task_name: string;
    celery_task_args?: (string | null);
    celery_task_kwargs?: (string | null);
    scheduled_time?: (string | null);
    periodic_schedule_type?: (PeriodicScheduleType | null);
    crontab_minute?: (string | null);
    crontab_hour?: (string | null);
    crontab_day_of_week?: (string | null);
    crontab_day_of_month?: (string | null);
    crontab_month_of_year?: (string | null);
    interval_seconds?: (number | null);
    interval_minutes?: (number | null);
    interval_hours?: (number | null);
    interval_days?: (number | null);
    status?: TaskStatus;
    enabled?: boolean;
    last_run_time?: (string | null);
    next_run_time?: (string | null);
    celery_task_id?: (string | null);
};

export type TaskExecutionPublic = {
    id: string;
    task_id: string;
    task_name?: (string | null);
    celery_task_name?: (string | null);
    celery_task_id: string;
    celery_task_args?: (string | null);
    celery_task_kwargs?: (string | null);
    status: string;
    started_at?: (string | null);
    completed_at?: (string | null);
    result?: (string | null);
    traceback?: (string | null);
    worker?: (string | null);
    runtime?: (number | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type TaskExecutionsPublic = {
    executions: Array<TaskExecutionPublic>;
    total: number;
};

export type TaskPublic = {
    id: string;
    name: string;
    description?: (string | null);
    task_type: TaskType;
    celery_task_name: string;
    celery_task_args?: (string | null);
    celery_task_kwargs?: (string | null);
    scheduled_time?: (string | null);
    periodic_schedule_type?: (PeriodicScheduleType | null);
    crontab_minute?: (string | null);
    crontab_hour?: (string | null);
    crontab_day_of_week?: (string | null);
    crontab_day_of_month?: (string | null);
    crontab_month_of_year?: (string | null);
    interval_seconds?: (number | null);
    interval_minutes?: (number | null);
    interval_hours?: (number | null);
    interval_days?: (number | null);
    status: TaskStatus;
    enabled: boolean;
    last_run_time?: (string | null);
    next_run_time?: (string | null);
    celery_task_id?: (string | null);
    owner?: (UserPublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type TasksPublic = {
    tasks: Array<TaskPublic>;
    total: number;
};

/**
 * 任务状态
 */
export type TaskStatus = 'pending' | 'running' | 'success' | 'failed' | 'revoked' | 'disabled';

/**
 * 任务类型
 */
export type TaskType = 'async' | 'scheduled' | 'periodic';

export type TaskUpdate = {
    name?: (string | null);
    description?: (string | null);
    task_type?: (TaskType | null);
    celery_task_name?: (string | null);
    celery_task_args?: (string | null);
    celery_task_kwargs?: (string | null);
    scheduled_time?: (string | null);
    periodic_schedule_type?: (PeriodicScheduleType | null);
    crontab_minute?: (string | null);
    crontab_hour?: (string | null);
    crontab_day_of_week?: (string | null);
    crontab_day_of_month?: (string | null);
    crontab_month_of_year?: (string | null);
    interval_seconds?: (number | null);
    interval_minutes?: (number | null);
    interval_hours?: (number | null);
    interval_days?: (number | null);
    status?: (TaskStatus | null);
    enabled?: (boolean | null);
    last_run_time?: (string | null);
    next_run_time?: (string | null);
    celery_task_id?: (string | null);
    owner_id?: (string | null);
};

export type Token = {
    access_token: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    username?: (string | null);
    full_name?: (string | null);
    avatar?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    password: string;
    role_id?: (string | null);
};

export type UserPrivate = {
    id: string;
    username: string;
    full_name?: (string | null);
    avatar?: (string | null);
    role?: (RolePublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    email: string;
    is_active: boolean;
    is_superuser: boolean;
};

export type UserPublic = {
    id: string;
    username: string;
    full_name?: (string | null);
    avatar?: (string | null);
    role?: (RolePublic | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPrivate = {
    users: Array<UserPrivate>;
    total: number;
};

export type UserUpdate = {
    email?: (string | null);
    username?: (string | null);
    full_name?: (string | null);
    avatar?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    password?: (string | null);
    role_id?: (string | null);
};

export type UserUpdateMe = {
    email?: (string | null);
    username?: (string | null);
    full_name?: (string | null);
    avatar?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ApiReadApisResponse = (ApiTreePublic);

export type ApiCreateApiData = {
    requestBody: ApiCreate;
};

export type ApiCreateApiResponse = (ApiPublic);

export type ApiReadApiData = {
    apiId: string;
};

export type ApiReadApiResponse = (ApiPublic);

export type ApiUpdateApiData = {
    apiId: string;
    requestBody: ApiUpdate;
};

export type ApiUpdateApiResponse = (ApiPublic);

export type ApiDeleteApiData = {
    apiId: string;
};

export type ApiDeleteApiResponse = (Message);

export type ApiReadApiPoliciesData = {
    apiId: string;
};

export type ApiReadApiPoliciesResponse = (Array<string>);

export type ApplicationReadApplicationsData = {
    limit?: number;
    skip?: number;
};

export type ApplicationReadApplicationsResponse = (ApplicationsPublic);

export type ApplicationCreateApplicationData = {
    requestBody: ApplicationCreate;
};

export type ApplicationCreateApplicationResponse = (ApplicationPrivate);

export type ApplicationReadApplicationData = {
    appId: string;
};

export type ApplicationReadApplicationResponse = (ApplicationPublic);

export type ApplicationUpdateApplicationData = {
    appId: string;
    requestBody: ApplicationUpdate;
};

export type ApplicationUpdateApplicationResponse = (ApplicationPublic);

export type ApplicationDeleteApplicationData = {
    appId: string;
};

export type ApplicationDeleteApplicationResponse = (Message);

export type CeleryGetWorkersResponse = (unknown);

export type CeleryGetActiveTasksResponse = (unknown);

export type CeleryGetScheduledTasksResponse = (unknown);

export type CeleryGetReservedTasksResponse = (unknown);

export type CeleryGetTaskStatusData = {
    taskId: string;
};

export type CeleryGetTaskStatusResponse = (unknown);

export type CeleryRevokeTaskData = {
    taskId: string;
};

export type CeleryRevokeTaskResponse = (unknown);

export type CeleryGetCeleryStatsResponse = (unknown);

export type CeleryGetRegisteredTasksResponse = (unknown);

export type GroupReadGroupsData = {
    limit?: number;
    skip?: number;
};

export type GroupReadGroupsResponse = (GroupsPublic);

export type GroupCreateGroupData = {
    requestBody: GroupCreate;
};

export type GroupCreateGroupResponse = (GroupPublic);

export type GroupReadGroupData = {
    groupId: string;
};

export type GroupReadGroupResponse = (GroupPublic);

export type GroupUpdateGroupData = {
    groupId: string;
    requestBody: GroupUpdate;
};

export type GroupUpdateGroupResponse = (GroupPublic);

export type GroupDeleteGroupData = {
    groupId: string;
};

export type GroupDeleteGroupResponse = (Message);

export type ItemReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemReadItemsResponse = (ItemsPublic);

export type ItemCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemCreateItemResponse = (ItemPublic);

export type ItemReadItemData = {
    itemId: string;
};

export type ItemReadItemResponse = (ItemPublic);

export type ItemUpdateItemData = {
    itemId: string;
    requestBody: ItemUpdate;
};

export type ItemUpdateItemResponse = (ItemPublic);

export type ItemDeleteItemData = {
    itemId: string;
};

export type ItemDeleteItemResponse = (Message);

export type LoginGetLoginConfigResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_Login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LoginRegisterData = {
    requestBody: UserRegister;
};

export type LoginRegisterResponse = (UserPublic);

export type LoginLoginOidcResponse = (unknown);

export type LoginLoginOidcCallbackData = {
    code: string;
};

export type LoginLoginOidcCallbackResponse = (unknown);

export type LoginLogoutOidcResponse = (unknown);

export type MenuReadMenusResponse = (Array<MenuTreeNode>);

export type MenuCreateMenuData = {
    requestBody: MenuCreate;
};

export type MenuCreateMenuResponse = (MenuTreeNode);

export type MenuReadMenuData = {
    menuId: string;
};

export type MenuReadMenuResponse = (MenuTreeNode);

export type MenuUpdateMenuData = {
    menuId: string;
    requestBody: MenuUpdate;
};

export type MenuUpdateMenuResponse = (MenuTreeNode);

export type MenuDeleteMenuData = {
    menuId: string;
};

export type MenuDeleteMenuResponse = (Message);

export type MenuReadMenuPoliciesData = {
    menuId: string;
};

export type MenuReadMenuPoliciesResponse = (Array<string>);

export type OpenApiOpenapiDemoResponse = (Message);

export type PolicyReadPoliciesResponse = (Array<Policy>);

export type PolicyAddPolicyData = {
    requestBody: Policy;
};

export type PolicyAddPolicyResponse = (boolean);

export type PolicyRemovePolicyData = {
    requestBody: Policy;
};

export type PolicyRemovePolicyResponse = (boolean);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPrivate);

export type RoleReadRolesData = {
    limit?: number;
    skip?: number;
};

export type RoleReadRolesResponse = (RolesPublic);

export type RoleCreateRoleData = {
    requestBody: RoleCreate;
};

export type RoleCreateRoleResponse = (RolePublic);

export type RoleReadRoleData = {
    roleId: string;
};

export type RoleReadRoleResponse = (RolePublic);

export type RoleUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RoleUpdateRoleResponse = (RolePublic);

export type RoleDeleteRoleData = {
    roleId: string;
};

export type RoleDeleteRoleResponse = (Message);

export type SettingsGetSettingsResponse = (unknown);

export type SettingsUpdateSettingsData = {
    requestBody: SettingsUpdate;
};

export type SettingsUpdateSettingsResponse = (unknown);

export type TaskReadTasksData = {
    limit?: number;
    skip?: number;
};

export type TaskReadTasksResponse = (TasksPublic);

export type TaskCreateTaskData = {
    requestBody: TaskCreate;
};

export type TaskCreateTaskResponse = (TaskPublic);

export type TaskGetRegisteredTasksResponse = (Array<(string)>);

export type TaskReadTaskData = {
    taskId: string;
};

export type TaskReadTaskResponse = (TaskPublic);

export type TaskUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TaskUpdateTaskResponse = (TaskPublic);

export type TaskDeleteTaskData = {
    taskId: string;
};

export type TaskDeleteTaskResponse = (Message);

export type TaskTriggerTaskData = {
    taskId: string;
};

export type TaskTriggerTaskResponse = (TaskPublic);

export type TaskEnableTaskData = {
    taskId: string;
};

export type TaskEnableTaskResponse = (TaskPublic);

export type TaskDisableTaskData = {
    taskId: string;
};

export type TaskDisableTaskResponse = (TaskPublic);

export type TaskGetAllTaskExecutionsData = {
    limit?: number;
    skip?: number;
};

export type TaskGetAllTaskExecutionsResponse = (TaskExecutionsPublic);

export type TaskGetExecutionData = {
    executionId: string;
};

export type TaskGetExecutionResponse = (TaskExecutionPublic);

export type TaskDeleteExecutionData = {
    executionId: string;
};

export type TaskDeleteExecutionResponse = (Message);

export type TaskGetTaskExecutionStatusData = {
    taskId: string;
};

export type TaskGetTaskExecutionStatusResponse = (unknown);

export type TaskGetTaskExecutionsData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type TaskGetTaskExecutionsResponse = (TaskExecutionsPublic);

export type UserReadUsersData = {
    limit?: number;
    offset?: number;
};

export type UserReadUsersResponse = (UsersPrivate);

export type UserCreateUserData = {
    requestBody: UserCreate;
};

export type UserCreateUserResponse = (UserPrivate);

export type UserReadUserMeResponse = (UserPrivate);

export type UserDeleteUserMeResponse = (Message);

export type UserUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UserUpdateUserMeResponse = (UserPrivate);

export type UserUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UserUpdatePasswordMeResponse = (Message);

export type UserRegisterUserData = {
    requestBody: UserRegister;
};

export type UserRegisterUserResponse = (UserPublic);

export type UserReadUserByIdData = {
    userId: string;
};

export type UserReadUserByIdResponse = (UserPublic);

export type UserUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UserUpdateUserResponse = (UserPublic);

export type UserDeleteUserData = {
    userId: string;
};

export type UserDeleteUserResponse = (Message);

export type UserForceLogoutData = {
    userId: string;
};

export type UserForceLogoutResponse = (Message);

export type UserReadUserMenuResponse = (Array<MenuTreeNode>);

export type UserUploadAvatarData = {
    formData: Body_User_upload_avatar;
};

export type UserUploadAvatarResponse = (UserPublic);

export type UtilTestEmailData = {
    emailTo: string;
};

export type UtilTestEmailResponse = (Message);

export type UtilHealthCheckResponse = (boolean);