"""Add task_name to TaskExecution

Revision ID: 093bf42a309c
Revises: 330172ed7a0b
Create Date: 2025-12-03 23:05:50.256333

"""
from typing import Union, Sequence

import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '093bf42a309c'
down_revision: Union[str, None] = '330172ed7a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_executions', sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('task_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('task_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('task_executions', 'result',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('task_executions', 'traceback',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('task_executions', 'args',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('task_executions', 'kwargs',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_task_executions_deleted_at'), 'task_executions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=True)
    op.drop_constraint(op.f('task_executions_task_id_fkey'), 'task_executions', type_='foreignkey')
    op.create_foreign_key(None, 'task_executions', 'tasks', ['task_id'], ['id'])
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tasks', 'task_args',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tasks', 'task_kwargs',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=True)
    op.drop_column('tasks', 'execution_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('execution_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tasks', 'task_kwargs',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'task_args',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'task_executions', type_='foreignkey')
    op.create_foreign_key(op.f('task_executions_task_id_fkey'), 'task_executions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_deleted_at'), table_name='task_executions')
    op.alter_column('task_executions', 'kwargs',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_executions', 'args',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_executions', 'traceback',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_executions', 'result',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('task_executions', 'task_name')
    # ### end Alembic commands ###
