"""Add SystemSetting table

Revision ID: 330172ed7a0b
Revises: add_periodic_fields
Create Date: 2025-12-03 20:27:01.409805

"""
from typing import Union, Sequence

import sqlmodel
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '330172ed7a0b'
down_revision: Union[str, None] = 'add_periodic_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.alter_column('applications', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('groups', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('items', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('groups', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('applications', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('systemsetting')
    # ### end Alembic commands ###
