"""init

Revision ID: 7c9850f22026
Revises: 
Create Date: 2025-11-29 23:38:48.556510
"""
from typing import Union, Sequence

import sqlmodel
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7c9850f22026'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Casbin Rules
    op.create_table('casbin_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v0', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v3', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v4', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('v5', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Roles
    op.create_table('roles',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'])
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=True)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'])
    # Users
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oidc_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_oidc_sub'), 'users', ['oidc_sub'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'])
    # Apis
    op.create_table('apis',
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apis_group'), 'apis', ['group'])
    op.create_index(op.f('ix_apis_name'), 'apis', ['name'])
    op.create_index(op.f('ix_apis_path'), 'apis', ['path'])
    op.create_index(op.f('ix_apis_method'), 'apis', ['method'])
    op.create_index(op.f('ix_apis_id'), 'apis', ['id'], unique=True)
    op.create_index(op.f('ix_apis_deleted_at'), 'apis', ['deleted_at'])
    # Menus
    op.create_table('menus',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('to', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('clazz', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=True)
    op.create_index(op.f('ix_menus_deleted_at'), 'menus', ['deleted_at'])
    # Groups
    op.create_table('groups',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'])
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=True)
    op.create_index(op.f('ix_groups_deleted_at'), 'groups', ['deleted_at'])
    # Group - Member
    op.create_table('group_member_link',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    # Applications
    op.create_table('applications',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'])
    op.create_index(op.f('ix_applications_app_id'), 'applications', ['app_id'], unique=True)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=True)
    op.create_index(op.f('ix_applications_deleted_at'), 'applications', ['deleted_at'])
    # Items
    op.create_table('items',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'])
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=True)
    op.create_index(op.f('ix_items_deleted_at'), 'items', ['deleted_at'])
    # Tasks
    op.create_table('tasks',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('celery_task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('celery_task_args', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('celery_task_kwargs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('periodic_schedule_type', sa.String(length=20), nullable=True),
    sa.Column('crontab_minute', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('crontab_hour', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('crontab_day_of_week', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('crontab_day_of_month', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('crontab_month_of_year', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'])
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=True)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'])
    # Task Executions
    op.create_table('task_executions',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('celery_task_args', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('celery_task_kwargs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('worker', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_executions_celery_task_id'), 'task_executions', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=True)
    op.create_index(op.f('ix_task_executions_deleted_at'), 'task_executions', ['deleted_at'])
    # System Settings
    op.create_table('system_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # System Settings
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # Task Executions
    op.drop_index(op.f('ix_task_executions_deleted_at'), table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_celery_task_id'), table_name='task_executions')
    op.drop_table('task_executions')
    # Tasks
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_table('tasks')
    # Items
    op.drop_index(op.f('ix_items_deleted_at'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    # Applications
    op.drop_index(op.f('ix_applications_deleted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_app_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_table('applications')
    # Group - Member
    op.drop_table('group_member_link')
    # Groups
    op.drop_index(op.f('ix_groups_deleted_at'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    # Menus
    op.drop_index(op.f('ix_menus_deleted_at'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    # Apis
    op.drop_index(op.f('ix_apis_deleted_at'), table_name='apis')
    op.drop_index(op.f('ix_apis_id'), table_name='apis')
    op.drop_index(op.f('ix_apis_method'), table_name='apis')
    op.drop_index(op.f('ix_apis_path'), table_name='apis')
    op.drop_index(op.f('ix_apis_name'), table_name='apis')
    op.drop_index(op.f('ix_apis_group'), table_name='apis')
    op.drop_table('apis')
    # Users
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_oidc_sub'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Roles
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # Casbin rules
    op.drop_table('casbin_rules')
    # ### end Alembic commands ###
